### ISSUE TITLE
[BUG] Gravity Loss Event Disables Space Drift

### ISSUE THREAD

**Issue by l3lackk9** [Willburd/Outpost21#101]
Centcomm Gravity Loss event interacts strangely with the Zero-G in the Orbital Reclamation Yard.  Game detects player as "weightless" after gravity is restored, however, it completely disables the ability to drift through space after shoving off a solid surface.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/c133cc343ebfe225edcd895c517fdd2a7bf43021
