### ISSUE TITLE
Shadekin can't be resleeved

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#104]
#### Brief description of the bug
Shadekin, upon brutal expiration, cannot be resleeved or rejoin the round

#### What you expected to happen
While this is probably fine for colored eyes, black-eye shadekin should be able to be resleeved, especially if the code's been changed to allow vox and such to be able to be resleeved

#### Steps to reproduce
- Be a shadekin of any type
- Die
- Cry

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/b8626dfb8a165c601233020fa096e3cadd89d6c7
