### ISSUE TITLE
Blast doors don't update light pass when destroyed.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#105]
#### Brief description of the bug
Blast doors block light and vision, acting as a solid wall, when ran over by a tank.

#### What you expected to happen
Crashing through a blast door should fully remove the vision restriction on where the blast door was, as though it had been opened.

#### Steps to reproduce
- Hop in a tank
- Crash through the garage door like the scene from Aliens
- Hop out of the tank
- Realize you can't see through the hole where the door used to be.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/b0f33f576957e49a8437e3cfd809ea6da5ca2d11
