### ISSUE TITLE
Method of viewing tank externals via cameras

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#106]
#### Brief overview of the feature
You can see tank interiors through security cameras
You should be able to see outside the tank, even if limited, as a way of detecting where the tank is.
OR give them a GPS tracker.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/a30dd13d34f516d67fdb5e49d852b1651f77afbf
