### ISSUE TITLE
[BUG] Cigarette Description Wierdness

### ISSUE THREAD

**Issue by l3lackk9** [Willburd/Outpost21#107]
![image](https://github.com/Willburd/Outpost21/assets/116856005/61c37b70-1b1c-4551-a488-577f828bee2e)
Jericho cigarette has a weird text character in its description.

Other cigarettes may have the same problem.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/d67439d45c9d56cb0660850105a8d77c4f7ac1e7
