### ISSUE TITLE
Borg radio channels not accessing all appropriate channels

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#109]
#### Brief description of the bug
Each borg is supposed to have access to every main channel, and a private "Robot Binary" channel. Currently, they can only access common, and their department. Robot binary is entirely nonfunctional, either as language or private radio frequency, as intended.
I suspect Yawn or Virgo disabled this in the past because "Oh it makes antag borgs too strong" or some trash excuse.

#### Steps to reproduce
- Be a borg
- Attempt to secretly converse with your other borg-friends with :b 
- Realize that doesn't work. Not even as AI.
- Attempt to communicate privately to command staff.
- Realize you can't hear them, and you can't talk to them on any channel because you were a fool and picked a service borg and can't talk to any department except over common.
- Cry lots because any hope you had of succeeding as an antag borg has been destroyed, and departments can't privately address issues with you, so they just ignore you more than borgs already get ignored.

**Comment by Willburd** [comment]
robot and drone talk are triggered with , b and d for borg and drone
