### ISSUE TITLE
[Req] "Emergency Security Access" card.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#110]
#### Brief overview of the feature
Similar idea to the captain's spare ID card, an ID card kept in the bridge that has access to security, and blue armory. (Not red) for usage in emergencies when there is no current security.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/4819a463fd65b77ba1d7373b69035a4e1e848293
