### ISSUE TITLE
Security Oties need security access

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#111]
#### Brief description of the bug
Security Oties need security access. Currently if they try to follow you through security and fall behind, they'll start smashing on doors and windows, potentially killing themselves on electrified windows while trying to follow.

#### What you expected to happen
Security Oties should be able to follow officers through security.

#### Steps to reproduce
- Pet otie
- Encourage them to follow
- Go too far ahead
- Watch them smash into doors and windows, breaking them, just to follow you.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/feb56a4b60b3640a833a623ed0b8a077f4e577c5
