### ISSUE TITLE
Rig weight

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#112]
#### Brief description of the bug
Rigs currently slow you down more when held as an item or worn only on the back, than when fully deployed and engaged. This seems to make no sense, as it makes them more beneficial when engaged, giving you armor, internals, and a back slot, than when they're simply carried or only removing your backpack slot.

#### What you expected to happen
When a rig is deployed, it gives you; armor, internals access, any modules the rig has, magboots, and allows you to wear your back slot to carry a dufflebag or backpack. That should be when the rig slows you down the most.

#### Other Relevant Information
This is caused by the rig being flagged as "ITEMSIZE_HUGE" which is appropriate and prevents them from being smuggled in backpacks, but other flags should be investigated to see about fixing the weight forced by the huge item weight.

**Comment by Willburd** [comment]
Resolved, but unbalanced, in https://github.com/Willburd/Outpost21/commit/dd88e669aa16fb4fbbb9ff7cb0266854c08b0bcd
