### ISSUE TITLE
[Request] Random *cough emote while smoking

### ISSUE THREAD

**Issue by l3lackk9** [Willburd/Outpost21#113]
While holding an item designated as a cigarette or cigar in your mouth or ear slot while it is lit, your character should use the *cough emote at random intervals.

This could also happen if you "take a drag" on the item by a lit cigarette or cigar in your hand on yourself, with a small delay.

**Comment by Willburd** [comment]
This can be achieved with chronic cough disability if your character is a regular smoker.
