### ISSUE TITLE
Fires

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#114]
#### Brief overview of the feature
Okay this is going to be a huge fucking nightmare to code but I feel the game could benefit from it.

Idea: An effect of fire that slowly burns in a room. Potentially multiple sizes. Burns wires, wood floors, tables, structures, people, etc.
Fires consume oxygen, and output Co2 and heat. Fires of a certain size automatically set off fire alarms in their area to help automatically contain their spread.
If there's no more fuel or oxygen, it burns out. If water is sprayed on it from a fire extinguisher it'll also instantly put it out.
A small electrical fire can be a new event to just start a small spark.

A burnable flag will need to be added to most things to determine if it can burn or not.
Fires touching phoron crystals, phoron tables, etc, either cause the fire to go utterly insane, or explode.

Burnable tag with multiple stages. 0 = Nonflammable. 1 = Flammable. 2 = Flammable with addition.
Explosive tag? If an object is incinerated, it detonates.

**Comment by Willburd** [comment]
Forwarded to https://github.com/Willburd/CHOMPost21/issues/215
