### ISSUE TITLE
Automagic records

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#116]
#### Brief overview of the feature
Records are amazing. Employment history, certs, skills.. Security records with your arrest reasons and why.. Medical records so you can make your nebulizer allergy known...
And nobody uses them because they're horrible to update, don't update in-round, and are often not needed. Let's fix that.

- All records could pre-fill the text box with an empty template, to remove hesitation and fear of "how do I format this?" as well as giving a good example. Makes records a LOT easier.

#### Medical records:
- Have it pull from allergies to give proper allergies and prescriptions for it.
- Have it pull from disabilities
- Give the ability to set a default/preferred language from character creation, instead of forced species default. Records can pull from this to show "preferred language."
- Have it automatically pull blood type.

#### Security records
- Updates from inputted arrests on station.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/1085022cec36650d874896b4547acaa6ccf9aaec
