### ISSUE TITLE
Being Chu'ified destroys your main clothing, and all attached items/holstered weapons

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#125]
#### Brief description of the bug
When corrupted by a chu, your clothing is destroyed, and all items holstered in holsters are also deleted.

#### Steps to reproduce
- Attach things to your suit.
- Attach holsters
- holster a weapon
- Get eaten by a chu
- lose everything attached to your suit.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/3c9932b06f0db313c8b7ae2516dc320ac500a3db
