### ISSUE TITLE
"Trap" Map marker

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#127]
#### Brief overview of the feature
A randomizer for generic, non-destructive traps in maintenance or other areas.

Frayed wires should be able to pull from any wire under them, to pick a random (valid) direction from a wire under it to make a node for. (matching wire color?)
The map marker would include frayed wires, bear traps, mouse traps, and other non-destructive traps to catch people off guard, and make maintenance more unpredictable as to the location of hazards.

This'll be used for traps in maintenance that specifically shouldn't include things like gasses, explosives, and other "destructive" methods.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/d940138629d45a39acfe0d208562d33c591ce596
