### ISSUE TITLE
Cigs need to handle reagents differently for long lasting cigars

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#129]
#### Brief description of the bug
Cigars do not contain nicotine and cannot sate nicotine addictions. But nicotine comes from tobacco and that's basically all of what a cigar is

#### Steps to reproduce
- Have a nicotine addiction
- smoke a cigar
- Still get messages and symptoms of withdrawl

**Comment by Willburd** [comment]
Changed, this is now a feature request for cigs to slowly give their nicotine over the course of their smoke time instead of instantly at the start

**Comment by Willburd** [comment]
Corrected using the already existing code that does the above

**Comment by Willburd** [comment]
nevermind

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/94ac78f6211753b402a4e01eb35222e18b824386
