### ISSUE TITLE
Inconsistent spider verbs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#130]
#### Brief description of the bug
Nurse spiders/empresses are able to eat food from dead creatures to spawn eggs and make webs. But when under player control, neither of these verbs show up, making antag nurse spiders impossible.
(Nurse spiders should also have ventcrawl ability when under player control for that purpose)

#### Steps to reproduce
- Spawn a nurse spider.
- Inhabit it.
- Realize you're worthless
- Cry in all your antag hopes being destroyed.

**Comment by Willburd** [comment]
Attacking targets allow webbing and egg injection already. won't fix
