### ISSUE TITLE
Mobs continue to be able to attack predators after being eaten

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#138]
#### Brief description of the bug
Mobs, when eaten, are able to attack their predators. Including weird behavior where they're able to knock you down and eat you after being eaten, leading to recursive vore that breaks both creatures.
This is a bug Virgo made years ago and just decided was "intended behavior" because they can't be bothered to fix it. Apparently this is a known issue that happened when Virgo updated their ai_holders.

Intended behavior:
Mob gets eaten, drops all aggro and is unable to target or attack anything. They should become passive, except potentially struggling out.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/0f6dbb17264cd4e3989e283e9f3592d90f065e24
