### ISSUE TITLE
Plantavator not accepting inputs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#139]
#### Brief description of the bug
The plantavator is not accepting inputs of grown items from either top or bottom end.

#### What you expected to happen
Grown items and raw foods should be able to be placed in the plantavator for easy transport from upstairs to downstairs. (or vice versa if for some reason you need that)

#### Steps to reproduce
- Grow food
- Attempt to place food in plantavator for easy transport
- Cry

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/99f027fe8371b5114f33cca1a9b918181c201daf
