### ISSUE TITLE
Body scanner not showing shrapnel, or items lodged in wounds?

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#146]
#### Brief description of the bug

Body scanners don't show shrapnel, bullets, or presumably knives and other objects stuck into wounds. At most you get a "foreign objects detected" that doesn't say where, and isn't specific enough to tell if its implants or not. This makes it nearly impossible to treat gunshot wounds and landmine shrapnel.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/9584d87f517f0d80d17216576799ac3a1b9c1fa8
