### ISSUE TITLE
Autolathe items require plasteel, but cannot be inserted

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#154]
#### Brief description of the bug
Certain items from an autolathe require plasteel. Plasteel cannot be inserted into a lathe, as it breaks them down into steel and platinum, rather than maintaining it as plasteel.

#### Steps to reproduce
- Want to print a thing
- Insert plasteel
- Cry

**Comment by Willburd** [comment]
Not broken on chomp
