### ISSUE TITLE
You cannot unbuckle from boats

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#156]
#### Brief description of the bug
You can buckle yourself to the wooden dragon boats found in the caves, but cannot unbuckle from them. Leading to you potentially getting stuck.

#### Steps to reproduce
- Find a boat
- Buckle yourself to the boat to paddle it.
- Find a good, or bad, place to stop
- Attempt to unbuckle
- Cry as your life is now boat.
- Boat will consume all.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/00597bfc9ce534063f0bc14ba045179be8809eaa
