### ISSUE TITLE
Prosthetic intestines cannot be repaired, or installed?

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#157]
#### Brief description of the bug
Prosthetic intestines cannot be surgically installed into a patient, and cannot be repaired via nanopaste like other synthetic organs.

#### Steps to reproduce
- Have a patient with prosthetic intestines.
- Remove them from the patient after injury
- Attempt, and fail, to repair them.
- Attempt, and fail, to reinstall them.
- Realize you cannot make new ones.
- Wonder who made this specific plate of spaghet.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/fa1bd18b4ed157bd0af7658cd0a73a3cb2b651e0
