### ISSUE TITLE
Mice set off landmines

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#158]
#### Brief description of the bug
Mice and cockroaches can walk over landmines and detonate them.

#### What you expected to happen
Tiny mobs should not be able to set off landmines, like how they already avoid beartraps.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/e8ce455dc3d46ac532284fb4519c42b47b5e6ed1
