### ISSUE TITLE
[REQUEST] Add a "Blackjack Deck"

### ISSUE THREAD

**Issue by l3lackk9** [Willburd/Outpost21#159]
A 6-deck setup is required for playing blackjack effectively.  As such, I would like to see something similar implemented to the code.

In essence, a Blackjack deck is simply a casino deck multiplied six times in one deck, making it much, much easier to deal "hands" of cards to players when playing blackjack, allowing for the dealer to right click → examine a hand on the table to dictate how much the hand is worth, and if it busted or not.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/8745ccdd175405915db2736da4c35b062ee822ef
