### ISSUE TITLE
Alien scalpel is worse than standard ones.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#38]
The alien tools are meant to be hyper-advanced tools and tech, but it is worse than ones that can be made on station.

Alien scalpel, while faster, causes bleeding, and has the same failure rate as scalpels. It should be a bloodless cut, with less failure chance than the tier 3 laser scalpel to be in-line with the rest of the alien tools.

#### Steps to reproduce
- grab a tier 3 laser scalpel.
- Cut someone open.
- Be happy they don't bleed.
- grab an alien scalpel
- Realize they're bleeding.
- Cry in using the slower speed laser scalpel because it's a better end product.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/d5b5d96d797bc13adf384666c8a0c5b3c22418c5
