### ISSUE TITLE
Spinning in a chair doesn't spin the chair.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#40]
When using *spin in a chair, you spin, but the chair doesn't

The chair should spin with you, for peak spinning.

#### Steps to reproduce
- buckle yourself to a roller chair.
- type *spin.
- Watch yourself spin in the chair, with the chair remaining stationary
- Cry

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/92d8380ba1468b5c6936082b86ec0868e20ed6f8
