### ISSUE TITLE
Investigate "hovering" variable

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#41]
#### Brief overview of the feature
Is the hovering variable significantly from the flying variable in humanoids?

#### What you want to happen
Code improvement and optimization using a pre-built helper and not copy&paste spaghet.
Check to see if we can use the "hovering" variable that already exists in place of usage of Flying with winged characters.

#### Anything else you may wish to add:
- Sanity check landmines and maglev tracks to ensure they interact properly with flying/hovering.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/3b27cc97944d6f2e5ff744a513ce7fa68bb8d523
