### ISSUE TITLE
Circuit Imprinter uses Reagent ID instead of name when wanting refills.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#42]
When refilling a circuit imprinter, it checks for a reagent ID instead of a name.

Names are much more sane, and should be used instead of magic numbers. In game?

Ask will for more information, he submitted the original issue. I'm just porting it here for tracking.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/4ea7ed4b68ac60ad3c58a8e528c826ce31caa939
