### ISSUE TITLE
Rename Gas meters around the Incinerator

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#43]
Gas meter names are using a copy of another flow meter in atmospherics

The name of the meter should tell you exactly what its supposed to be analyzing, and the pipe its on. For ease of understanding the piping hell you're trying to figure out.

**Comment by Willburd** [comment]
Corrected in https://github.com/Willburd/Outpost21/commit/a85d75fe5ba3710c3166109916ecdb7a7c9c611e
