### ISSUE TITLE
[UI] SOP formatting needs to be improved on crew expectations.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#44]
SOP document formatting is wrong. it's becoming a giant blob of text instead of having line breaks when needed.

Documents should look nice for ease of reading and finding specific information.

Iggy hasn't yet fixed his hekkin formatting.

#### Steps to reproduce
- Open PDA
- Attempt to read the SOP and crew expectations like a good spaceman
- Cry as you can't read it because it's a giant wall of text beating you over the face.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/777f73d2f769c33b503199256fa0e3ab790d7637
