### ISSUE TITLE
Cargo loadable vending machine

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#45]
#### Brief overview of the feature
TG and other stations have a vending machine that starts empty. Cargo can unlock it, put in whatever items they want, set their price, link it to the cargo account for money (or their own), and re-lock it. Crew can then buy things from the vending machine.

#### What you want to happen
- Create a special vending machine that only cargo can unlock.
- This vending machine can be filled with totally legal, not stolen, goods for the station to buy back.
- Cargo will probably use it to steal every spare light box on the station, sell them for absurd prices, then go around stealing lights to add to the sale. That's funny.
- Possibly tie in more usages for cargo to buy things with the money. Maybe allowing them to use actual thalers from the cargo account instead of supply points?

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Willburd** [comment]
Replaced by https://github.com/Willburd/CHOMPost21/issues/63
