### ISSUE TITLE
[MAP] Additional landing sites at the reclamation yard

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#47]
#### Brief description of the bug
Currently, only one shuttle and the trawler can land. This makes it a problem if someone lands the trawler at a bad spot, or you need an actual station-sized evacuation. You're just forced to sit in your shuttle and cry, hoping they move their vessel.

#### What you expected to happen
Enough landing spots for the shuttles, even if it's off the station itself, forcing a spacewalk.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/5ced17ffec8951318339385bc2df7a8fff7834eb
