### ISSUE TITLE
Phone Spiders

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#49]
#### Brief overview of the feature
Holographic phone spiders that appear around holopoints and attack people that get too close. Fade after awhile?

#### What you want to happen
Basically a silly event that can be a problem. Referencing E-shui "active discouragement measures against spammers"
 
#### Anything else you may wish to add:
- Can look into Holocarp code to take inspiration from.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/49ccd695a4dfee3d1d4ee010b34c8887dac983e4
