### ISSUE TITLE
Virology love

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#50]
#### Brief overview of the feature
Virology needs love, with new virus features, disease types, etc.

#### What you want to happen
Need more symptom types, some that might even be beneficial, or at least harmless. Currently viruses are just insane with no real 'neutral' middle ground.
 
#### Anything else you may wish to add:
- Maybe parasites could fall under virology? Alternative treatments to them to pacify, or turn them beneficial?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/c34867b6acff9f217943ca861aec45e92bfab45c
