### ISSUE TITLE
Target painter

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#52]
#### Brief overview of the feature
An item that when a tile is clicked on, displays a laser like the laser pointers, and returns to you the coordinates of that tile. Specifically for usage in radioing or faxing central with coordinates to artillery strike.

#### What you want to happen
- Players can use the target painter to get the coordinate of something.
- Players can then send that to central.
- The bluespace artillery gun should be able to fire at exact coordinates for a strike to cause an explosion. Since we already have mass artillery strikes, why not precision?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/21b865b22ba2c98a0820aada6d5cb87cf1c12008
