### ISSUE TITLE
Improve picture UI and show ghosts

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#53]
#### Brief overview of the feature
Cameras should show ghosts at half alpha when they have their picture taken. Currently only says their name.

#### What you want to happen
- Take a picture of you and your friend
- See an extra person in the photo
- Scream
 
#### Anything else you may wish to add:
- This will likely involve a massive rework of how cameras actually take pictures because currently holy crap is it old spaghetti. Long stale and unseasoned.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/846e668826854b75a13c11565a2746fc2c44d6a9
