### ISSUE TITLE
Jils setting themselves on fire when using a lighter

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#55]
#### Brief overview of the feature
Jils should be able to set themselves on fire if they use a lighter. Because that's hilarious.

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/a5b9b1ba7fd0173645cd6f562a2bf5fcf232a5dc
