### ISSUE TITLE
Restrict ghost vision for players

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#56]
#### Brief overview of the feature
Apparently you can restrict ghosts to not be able to see certain areas? Great for secret keeping.

#### What you want to happen
Set flags in various maintenance areas so if someone is ghosting, they can't see what's in that area.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Willburd** [comment]
This codebase has the feature, but i've not located the code that handles it https://github.com/ARF-SS13/coyote-bayou

**Comment by Willburd** [comment]
Somewhat of an  attempt, resolved in: https://github.com/Willburd/Outpost21/commit/2905ea0366eb859dec142dcf89bfc78d0683f7bb
