### ISSUE TITLE
Tank sounds and horns.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#57]
#### Brief description of the bug
Tanks have no sounds. They're perfectly silent.

#### What you expected to happen
Tanks are loud as heck, and should be able to heard from pretty far away, helps with intimidation and helps antags escape from the overwhelming power of Greater Force.
Tanks should also have horns to warn people to move or get crushed.

#### Steps to reproduce
- Sit in the tank
- Vroom vroom.
- No actual vroom vroom, just sliding and occasional crunching of tiles and walls.
- Realize your tank is branded with the Mime seal of approval.

**Comment by Willburd** [comment]
I setup the code for it, resources needed
