### ISSUE TITLE
Borg eye sprites aren't correct.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#58]
#### Brief description of the bug
Borg eye and light sprites aren't layering properly. And aren't showing up

#### What you expected to happen
Borgs eyes, various markings, and other bits glow. Helping to spot them and tell their status, if they're on or off.

#### What actually happened
The lights aren't rendering, or are rendering on a lower level. They currently only appear when the borg is resting. Likely because those are hard-sprited and not using the fancy layers.

#### Steps to reproduce
- Be a borg
- Realize you have black, soulless eyes.
- Lay down and rejoin your eyes have returned.
- Stand up again and cry because they're gone.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/56238dcea1b524b1e2ea0798346d2fa37c959feb
