### ISSUE TITLE
[Spriting] Jilly bean custom sprite

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#64]
#### Brief overview of the feature
Jilly bean needs their own sprite

#### What you want to happen
Jilly bean's sprite should be the phone taped to their face. Maybe with a press badge on their chest?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/dca463677e5830fcd255846234a56fda3a32e9fb
