### ISSUE TITLE
Out of Game News

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#65]
#### Brief overview of the feature
Stuff like yawn's Sleepy Sergal, or Virgo's news outlet. Silly in-game news that can be found in game. I think through the newscaster?

#### What you want to happen
More world interaction, make things feel alive. Give subtle consequence to previous insane rounds.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/d4002d0dd0d6f10479a57d477a9214e137d640c2
