### ISSUE TITLE
Spacelube buff

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#67]
#### Brief overview of the feature
Currently, spacelube only slips you 3-4 tiles.
Spacelube should slip you all the way to the end, to allow for utterly insane slip and slides down the station (or down throats)

#### What you want to happen
Peak weeeeee
 
#### Anything else you may wish to add:
Probably need a sprite for space lubed/wet floors to make them a little more obvious.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/ad4b4371352b9e52644dcf860440e7ccbf3ded7b

**Comment by Willburd** [comment]
Resolved further in https://github.com/Willburd/Outpost21/commit/31c1bbaaadeef5d29ba474d4c89421a021d6631e
