### ISSUE TITLE
Incorrect logo in paperwork

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#68]
#### Brief description of the bug
When you write [logo] on a piece of paper, it draws the Nanotrasen logo.

#### What you expected to happen
We are not Nanotrasen, the logo should be E-Shui's corporate logo.

#### What actually happened
Signing papers results in the NT logo.

#### Steps to reproduce
- Try to be fancy
- Write [logo] to stamp your paper as official
- Realize it's another company's logo
- Commit sudoku for corporate betrayal.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/af2d6758aa0ab6ebe26e48c6c4242877cd5e6d1e
