### ISSUE TITLE
Magboots are not enzyme/water proof

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#69]
#### Brief description of the bug
Magboots aren't enzyme proof.

#### What you expected to happen
Magboots are space proof, they should be able to keep out water.

#### Steps to reproduce
- Put on magboots.
- Go outside
- Get your feet melted.
- Cry in betrayal.

**Comment by Willburd** [comment]
Issue was resolved by making suits themselves consider you airtight to enzyme rain, magboots are simply worn atop them, and behave like most other boots/impermeable clothing in the storm. with rain sloshing into them if you are not wearing anything that would cover them.
