### ISSUE TITLE
Body part: Butts

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#71]
#### Brief overview of the feature
Add Butts to humanoid creatures. Butts can be removed surgically, or with a wizard spell.

#### What you want to happen
Butts can also be used as a basis for a butt-bot, similar to a cleaning bot or medbot. Innately do nothing but can be a decent vessel for all sorts of shenanigans.
 
#### Anything else you may wish to add:
- will likely need sprites. Dionae don't have butts.

**Comment by Willburd** [comment]
vox diona:
TRY AS YOU MIGHT, THEY HAVE NO BUTT TO SMITE

**Comment by Willburd** [comment]
Mostly resolved in https://github.com/Willburd/Outpost21/commit/ad27c430b72190d94fd237c5b1e8d5d4ecfd624f missing buttbot
