### ISSUE TITLE
[BUG] Vermicetol recipe is broken.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#73]
#### Brief description of the bug
The written recipe for Vermicetol is incorrect and not processing.

#### What you expected to happen
2 parts bicaridine, 1 part 200v, and 5 units phoron catalyst should create the medication. This does not currently happen.

#### Steps to reproduce
- Grind up solar grub meat in a grinder to get 200v.
- Follow the listed recipes in current Virgo guides to create 60u bicard.
- Add 30u of 200v
- Add 10u Phoron
- Cry as nothing happens and you were deceived

**Comment by Willburd** [comment]
Chemical reaction is
required_reagents = list("kelotane" = 1, "dermaline" = 1, "shockchem" = 1, "phoron" = 0.1)

Will not fix, correct course of action will be to implement an ingame recipe system instead of using other people's wikis. Especially with our diverging codebases.
