### ISSUE TITLE
[BUG] Medical Kiosks don't report malignant organs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#75]
#### Brief description of the bug
The Medical Kiosks don't report malignant organs when doing a scan through them.

#### What you expected to happen
The kiosks are able to detect broken bones, internal bleeding, and other generic, but deeper information. They should be able to detect and warn about anatomical irregularities and to warn you to seek medical.

#### What actually happened
Using the kiosk with an organ present results in the "no anatomical issues detected" message from the kiosk.

#### Steps to reproduce
- Gain a malignant organ
- Get a check-up at a medical kiosk
- It says you're fine
- Go about your day because clearly the machine is correct.
- Explode from the piñata you were not warned about.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/94f43111f667273e35e2a15d030c38be4d931470
