### ISSUE TITLE
Player type shadekin when phased don't gain the spoopy alias

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#85]
#### Brief description of the bug
carbon/human shadekin don't have their name temporarily changed to "something" while phased.

#### What you expected to happen
simple mob shadekin, when phased, have their name set to "something" while phased, to provide a bit of spooky while phased and messing around with things. Selectable shadekin should be consistent with this.

#### What actually happened
Player shadekin do not have their name changed

#### Steps to reproduce
- Spawn mob "/mob/living/simple_mob/(shadekin)"
- Phase and emote/talk.
- Note that your name changed to "something"
- Spawn your player character shadekin via "spawn-character"
- Phase and emote/talk.
- Note your actual name is still used.

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/Outpost21/commit/9ba869f0a976102dc177217ae5ff18735ba7a3a1
