### ISSUE TITLE
[UI] Mining Braces Can Only Be Rotated Clockwise

### ISSUE THREAD

**Issue by l3lackk9** [Willburd/Outpost21#89]
Mining braces only have the "rotate clockwise" option when right clicking in the context menu.

![image](https://github.com/Willburd/Outpost21/assets/116856005/61e5679b-c3d8-408c-9a3a-96e280ece24f)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/bc558ac8865148e5edcfc12167ccf777ae0c1d79
