### ISSUE TITLE
Validate, and add, newspaper checks for jils

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/Outpost21#93]
Rolled up newspapers have a special interaction with mobs, when a player (or any creature) is swallowed, smacking the mob with a rolled up newspaper causes them to eject the prey without injuring the mob and triggering Retaliate code.

When smacked with rolled up newspapers, Jils should drop whatever they're holding, without killing them.

Unsure if this behavior currently exists, will need to check, and add if it does not.

#### Steps to reproduce
- Print newspaper from the station newscasters
- Roll it up in your hand. (I believe click on it with harm intent in your hand)
- Have someone get eaten by a mob.
- Smack it with the newspaper.
- Have a Jil pick up an item.
- Smack it with the newspaper
- Cry because I guarantee one or both of these isn't working.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/253fd4e01a3c42367aed1e8bb548ae84bee86146
