### ISSUE TITLE
Simple Mobs Starving

### ISSUE THREAD

**Issue by CrypticCadam** [Willburd/Outpost21#95]
When playing as a simple mob such as a chu or a jil, they still grow hungry over time or simple start out in a hungry state. It doesn't take much for them to slip in to a starving state.

The normal hunger system occurs as it would for more complicated mobs, like players.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/Outpost21/commit/c9a1b935f76459bfe040803952731e5a960eec35
